version: 2
jobs:
  build:
    docker:
      - image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "environment.yml" }}
      #     - v1-dependencies-

      - run:
          name: run linter
          command: |
              pip install flake8-colors
              flake8 --format="$FORMAT" --config=./setup.cfg --show-source

          environment:
              FORMAT: '${cyan}%(path)s${reset}:${yellow_bold}%(row)d${reset}:${green_bold}%(col)d${reset}: ${red_bold}%(code)s${reset} %(text)s'

      - run:
          name: install dependencies
          command: |
            # conda env create -q || conda env update -q
            # source activate adj
            conda install -qy pytest pytest-cov conda-build anaconda-client
            conda build --no-test .
            conda install --use-local rundmcmc
            conda install networkx

      # - save_cache:
      #     paths:
      #       - /opt/conda
      #     key: v1-dependencies-{{ checksum "environment.yml" }}

      - run:
          name: run tests
          command: |
            # source activate adj
            pytest -v --cov=rundmcmc tests
            conda install -c conda-forge codecov
            codecov

      - store_artifacts:
          path: test-reports
          destination: test-reports
